require('plugin.vim-airline')
require('plugin.vim-bufkill')
require('plugin.indentLine')
require('plugin.neoformat')
require('plugin.vim-easymotion')
require('plugin.nvim-treesitter')
require('plugin.vim-session')
