#!/bin/bash
#xbacklight -get | cut -d'.' -f 1
value=$(awk < /sys/class/backlight/intel_backlight/brightness '{print int($1+0.5)}')
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
backlight=$((value * 100 / max))

"$HOME/.config/i3/i3blocks-scripts/color-print" "$backlight" " $backlight" 80 50 30
