#!/bin/bash
# status=`upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state | awk '{print $2}'`
# percentage=`upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}'`
percentage=`acpi | grep 'Battery 0' | awk '{print $4}' | sed "s/,//"`

# echo "$status: $percentage"
echo "$percentage"
