#!/bin/bash

song=$(mpc current | cut -c 1-50)
status=$(mpc status %state%)
icon=$([ "$status" = "playing" ] && echo -n " " || echo -n "")

progress_percent=$(mpc status "%percenttime%" | awk '{print $1}' | tr % ' ')
progress_percent="${progress_percent:=0}" # fallback value

length=${#song}
split_index=$((length * progress_percent / 100 ))

escape_amp() {
    echo "${1//&/\&amp;}"
}

elapsed_part=$(escape_amp "${song:0:split_index}")
remaining_part=$(escape_amp "${song:split_index}")

echo -n "<b>${icon}${elapsed_part}</b>"
echo "$remaining_part"
