services:
  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379" # Redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
