#!/bin/bash
song=`playerctl --player=vlc metadata | grep title | awk '{for(i=3;i<=NF;++i)printf $i""FS ; print ""}'`
filename=`playerctl --player=vlc metadata | grep file | awk '{ print $3 }' | xargs basename | sed 's/%20/ /g'`

output=''

if [ "${#song}" -gt 0 ]; then
  output=$song
else
  output=$filename
fi

echo $output
