#!/usr/bin/env sh

_PS1_DIR="$_PROMPT_COLOR_BRIGHT_YELLOW$_PROMPT_COLOR_BOLD\W$_PROMPT_COLOR_RESET "
_PS1_PROMPT="$_PROMPT_COLOR_BRIGHT_RED\$$_PROMPT_COLOR_RESET"
__PS1_GIT_BRANCH() {
  if git branch --show-current &> /dev/null ; then
    echo -n -e "("
    git branch --show-current | tr -d '\n'
    echo -n -e ") "
  fi
}
_PS1_GIT_BRANCH="$_PROMPT_COLOR_BRIGHT_CYAN\$(__PS1_GIT_BRANCH)$_PROMPT_COLOR_RESET"

PS1="$_PS1_DIR$_PS1_GIT_BRANCH$_PS1_PROMPT "

# this indicates shell being opened in nnn
[ -n "$NNNLVL" ] && PS1="N$NNNLVL $PS1"
