hl.on("hyprland.start", function()
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("copyq")
	hl.exec_cmd("dunst")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("dropbox")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("~/bin/rw")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("gammastep")
	hl.exec_cmd("~/bin/xdg-hyprland-starter")
	hl.exec_cmd("hyprpm reload")
end)
