$font = FiraCode Nerd Font

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    inner_color = rgba(00000000)

    outer_color = rgb(d5c4a1)
    check_color = rgb(98971a)
    fail_color = rgb(cc241d)
    capslock_color = rgb(d79921)

    font_color = rgb(d5c4a1)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text =
    fail_text = $PAMFAIL

    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT[en,ir]

    font_size = 20

    onclick = hyprctl switchxkblayout all next

    color = rgb(d5c4a1)

    position = -40, 40
    halign = right
    valign = bottom
}
