matches:
  - trigger: ";4"
    replace: "4242424242424242"
  - trigger: ";e"
    replace: "{{secret_email}}"
    vars:
      - name: secret_email
        type: shell
        params:
          cmd: "echo $_SECRET_EMAIL"
  - trigger: ";gd"
    replace: "globalworkandtravel.com"
  - trigger: ";ge"
    replace: "{{secret_work_email}}"
    vars:
      - name: secret_work_email
        type: shell
        params:
          cmd: "echo $_SECRET_WORK_EMAIL"
  - trigger: ";gh"
    replace: "https://github.com/mazharz"
  - trigger: ";ld"
    replace: "https://www.linkedin.com/in/mazharz"
  - trigger: ";lsid"
    replace: "localhost:3000/?origin=gwat&session_id="
  - trigger: ";n"
    replace: "Mazhar Zandsalimi"
  - trigger: ";ph"
    replace: "{{secret_phone}}"
    vars:
      - name: secret_phone
        type: shell
        params:
          cmd: "echo $_SECRET_PHONE"
  - trigger: ";dt"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ";pw"
    replace: "{{secret_pass}}"
    vars:
      - name: secret_pass
        type: shell
        params:
          cmd: "echo $_SECRET_PASS"
  - trigger: ";daily"
    replace: |
      What I have done:

      -
      -

      What I will do:

      -
      -

      No blocks.
  - trigger: ";bk"
    replace: "(booking)"
  - trigger: ";wb"
    replace: "(website)"
  - trigger: ";vi"
    replace: "visa|relocat|permit|legal|sponsor"
  - trigger: ";127"
    replace: "http://127.0.0.1"
