[colors.bright]
black = "#1d2021"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#f9f5d7"
yellow = "#fabd2f"

[colors.footer_bar]
background = "#282828"
foreground = "#a89984"

[colors.hints.end]
background = "#a89984"
foreground = "#282828"

[colors.hints.start]
background = "#a89984"
foreground = "#282828"

[colors.line_indicator]
background = "#a89984"
foreground = "#282828"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#fbf1c7"
yellow = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#fbf1c7"

[colors.search.focused_match]
background = "#d79921"
foreground = "#282828"

[colors.search.matches]
background = "#a89984"
foreground = "#282828"

[colors.selection]
background = "#a89984"
text = "#282828"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.8

[cursor]
unfocused_hollow = true

